# Generated by Django 3.0.7 on 2020-06-15 18:38

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_attended', models.BooleanField(blank=True, null=True, verbose_name='has attended')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'attendee',
                'verbose_name_plural': 'attendees',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('read_time', models.IntegerField(default=0, verbose_name='read time')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('event_date', models.DateTimeField(verbose_name='event date')),
                ('total_guest', models.PositiveIntegerField(default=1, verbose_name='total of guest')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=events.models.event_upload_to, verbose_name='cover')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('session_type', models.CharField(choices=[('Talk', 'Talk'), ('Lighting Talk', 'Lighting Talk'), ('WorkShop', 'WorkShop')], max_length=100, verbose_name='session type')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Accepted', 'Accepted'), ('Denied', 'Denied')], default='Draft', max_length=10, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='events.Event', verbose_name='events')),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
            },
        ),
    ]
